### ISSUE TITLE
Billingdetails missing in orders

### ISSUE THREAD

**Issue by WeTurkstra** [best-brands/bol-com-retailer-api#3] opened 2021-06-03 09:52 UTC
Hey,

I seem to missing billings details in all the orders i fetch. Do you experience the same?
Is this another BOL.com mistake?

Thanks.

**Comment by harm-smits** [comment] 2021-06-03 10:09
I have no idea, can you check how old your order is?

**Comment by WeTurkstra** [comment] 2021-06-03 10:13
All the orders are from today. I used postman to call the api directly and it seems like the billingDetails are completly missing. 

Its a bit like the other issue we had a few weeks ago.

**Comment by harm-smits** [comment] 2021-06-03 10:15
They changed it again indeed -_-

**Comment by WeTurkstra** [comment] 2021-06-03 10:19
Great... hahaha. I love it when stuff randomly change. Our customers love it too😂.

Well i will make a workaround for it.

**Comment by harm-smits** [comment] 2021-06-03 10:22
Great, I am currently not in the office so please let me know what exactly you change so I can merge it accordingly. Especially interested in the change in raw response.

This is becoming quite the nuisance :/

**Comment by WeTurkstra** [comment] 2021-06-03 10:24
Yes ideed. Waht is will do is use the shipping Details for the billing details. I dont think its wise to do this in this repository.

There is no real way to fetch the billing details right now as far as i can see.

**Comment by harm-smits** [comment] 2021-06-03 10:27
https://twitter.com/bol_com/status/1400398349761748993?s=19

**Comment by harm-smits** [comment] 2021-06-03 10:32
Well, it's not a bug technically, since in the spec they define this as 'optional'. But it's needed for VAT invoices regardless.

**Comment by WeTurkstra** [comment] 2021-06-03 10:33
Yea. I saw your tweet earlier and retweeted it. So it looks like a technical issue on their side?

**Comment by harm-smits** [comment] 2021-06-03 10:46
Yep, no clue when it will be resolved though :(

**Comment by WeTurkstra** [comment] 2021-06-03 11:45
I looks like the orders are coming through right now.
It might be fixed!

**Comment by harm-smits** [comment] 2021-06-03 11:49
Yep, same here. I don't know why they don't test new deployments tbh. It scares me and I don't like it.

**Comment by harm-smits** [comment] 2021-06-03 13:37
Seeing as this has been resolved by bol.com, I am going to close this issue.

**Closed as completed by harm-smits** 2021-06-03 13:37 UTC
